server.port=8080
spring.application.name=iss-tracker

# N2YO API Key Placeholder
n2yo.api.key=843BMW-D5DKDM-9DXK98-5QLX
# ${N2YO_API_KEY}
# Spring Cache Configuration
spring.cache.type=simple

spring.mvc.favicon.enabled=false